"""empty message

Revision ID: 3a238c19e9c9
Revises: 6ec7e5fc8411
Create Date: 2019-08-26 14:13:35.155995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a238c19e9c9'
down_revision = '6ec7e5fc8411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
