"""empty message

Revision ID: 58774abb0b6f
Revises: 0af3588f9140
Create Date: 2019-08-25 15:13:04.657064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58774abb0b6f'
down_revision = '0af3588f9140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
